# Gear DB for the sim
'''
Template is: {  'name': 'name', 
                'attack_power': 0, 
                'agility': 0, 
                'crit_chance': 0, 
                'haste': 0, 
                'hit': 0,
                't1': False,
                'ZG_set': False,
                'RAQ_set':False,
                't2': False,
                'TAQ_set': False,
                'r10_set': False,
                'r13_set': False,
                't3': False},
'''
equipment_options = {
    'head': [
        # Done
        {'name': 'Cryptstalker Headpiece',
         'attack_power': 0,
         'agility': 31,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': True},
        {'name': 'Striker\'s Diadem',
         'attack_power': 0,
         'agility': 29,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': True,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Crown of Destruction',
         'attack_power': 44,
         'agility': 0,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Dragonstalker\'s Helm',
         'attack_power': 0,
         'agility': 27,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': True,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'R13 PVP Head',
         'attack_power': 0,
         'agility': 34,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': True,
         't3': False},
        {'name': 'R10 PVP Head',
         'attack_power': 0,
         'agility': 18,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': True,
         'r13_set': False,
         't3': False},
        {'name': 'Giantstalker\'s Helmet',
         'attack_power': 0,
         'agility': 23,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': True,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Crown of Tyranny',
         'attack_power': 40,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Backwood Helm',
         'attack_power': 0,
         'agility': 21,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'X-53 Ranger Ocular Implants',
         'attack_power': 0,
         'agility': 15,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Crown of Grobi',
         'attack_power': 0,
         'agility': 30,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False}
    ],
    'neck': [
        # Done
        {'name': 'Prestor\'s Talisman of Connivery',
         'attack_power': 0,
         'agility': 30,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False
         },
        {'name': 'Onyxia Tooth Pendant',
         'attack_power': 0,
         'agility': 12,
         'crit_chance': 1,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Mark of Fordring',
         'attack_power': 26,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Stormrage\'s Talisman of Seething',
         'attack_power': 26,
         'agility': 0,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Barbed Choker',
         'attack_power': 44,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Desert Wind Talisman',
         'attack_power': 0,
         'agility': 15,
         'crit_chance': 1,
         'haste': 1,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'The Eye of Hakkar',
         'attack_power': 40,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Maelstrom\'s Wrath',
         'attack_power': 0,
         'agility': 15,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': True,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Pendant of Celerity',
         'attack_power': 0,
         'agility': 15,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False},
        {'name': 'Bixxle\'s Necklade of Mastery',
         'attack_power': 0,
         'agility': 0,
         'crit_chance': 1,
         'haste': 1,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         't3': False}
    ],
    'shoulder': [
        # Done
        {'name': 'R13 PVP Shoulders',
         'attack_power': 0,
         'agility': 26,
         'crit_chance': 0,
         'haste': 1,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'R10 PVP Shoulders',
         'attack_power': 0,
         'agility': 18,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': True,
         'r13_set': False,
         't3': False},
        {'name': 'Abyssal Leather Shoulders of Striking',
         'attack_power': 0,
         'agility': 13,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Abyssal Mail Pauldrons of Striking',
         'attack_power': 0,
         'agility': 13,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Spaulders of the Unseen',
         'attack_power': 0,
         'agility': 22,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Wyrmtongue Shoulders',
         'attack_power': 0,
         'agility': 23,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Mantle of Wicked Revenge',
         'attack_power': 0,
         'agility': 30,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Truestrike Shoulders',
         'attack_power': 20,
         'agility': 0,
         'crit_chance': 0,
         'haste': 0,
         'hit': 2,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Wyrmhide Spaulders',
         'attack_power': 0,
         'agility': 0,
         'crit_chance': 0,
         'haste': 0,
         'hit': 2,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Shoulderpads of True Flight',
         'attack_power': 0,
         'agility': 18,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Giantstalker\'s Epaulets',
         'attack_power': 0,
         'agility': 24,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': True,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Shoulderguards of the Defiler',
         'attack_power': 20,
         'agility': 0,
         'crit_chance': 0,
         'haste': 0,
         'hit': 2,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Dragonstalker\'s Spaulders',
         'attack_power': 0,
         'agility': 23,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': True,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Cryptstalker Spaulders',
         'attack_power': 0,
         'agility': 29,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': True},

        {'name': 'Striker\'s Pauldrons',
         'attack_power': 0,
         'agility': 26,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': True,
         'r10_set': False,
         'r13_set': False,
         't3': False},

        {'name': 'Zandalar Predator\'s Mantle',
         'attack_power': 0,
         'agility': 22,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': True,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False}
    ],
    'back': [
        # done
        {'name': 'Shroud of Dominion',
         'attack_power': 50,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cloak of the Fallen God',
         'attack_power': 0,
         'agility': 26,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Veil of Nightmare',
         'attack_power': 32,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cloak of Firemaw',
         'attack_power': 50,
         'agility': 0,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Sandstalker\'s Shroud',
         'attack_power': 0,
         'agility': 19,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Shadow-Weaver\'s Cape',
         'attack_power': 50,
         'agility': 10,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cloak of Shrouded Mists',
         'attack_power': 0,
         'agility': 22,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cloak of Concentrated Hatred',
         'attack_power': 0,
         'agility': 16,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Puissant Cape',
         'attack_power': 40,
         'agility': 0,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Windshear Cape',
         'attack_power': 0,
         'agility': 15,
         'crit_chance': 0,
         'haste': 1,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Zulian Tigerhide Cloak',
         'attack_power': 0,
         'agility': 13,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cloak of the Unseen Path',
         'attack_power': 0,
         'agility': 17,
         'crit_chance': 0,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': True,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cape of the Black Baron',
         'attack_power': 20,
         'agility': 15,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Shadow Prowler\'s Cloak',
         'attack_power': 0,
         'agility': 17,
         'crit_chance': 0,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Kirin Tor Shawl of Persecution',
         'attack_power': 0,
         'agility': 8,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False}
    ],
    'chest': [
        # done
        {'name': 'Crypstalker Tunic',
         'attack_power': 0,
         'agility': 45,
         'crit_chance': 1,
         'haste': 0,
         'hit': 1,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': True},
        {'name': 'Striker\'s Hauberk',
         'attack_power': 0,
         'agility': 39,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': True,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Dragonstalker\'s Breastplate',
         'attack_power': 0,
         'agility': 34,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': True,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'R13 PVP Chest',
         'attack_power': 0,
         'agility': 34,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': True,
         't3': False},
        {'name': 'Breastplate of Earthen Might',
         'attack_power': 94,
         'agility': 0,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Obsidian Mail Tunic',
         'attack_power': 76,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'R10 PVP Chest',
         'attack_power': 0,
         'agility': 16,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': True,
         'r13_set': False,
         't3': False},
        {'name': 'Giantstalker\'s Breastplate',
         'attack_power': 0,
         'agility': 26,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': True,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Runed Bloodstainer Hauberk',
         'attack_power': 58,
         'agility': 0,
         'crit_chance': 1,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Savage Gladiator Chain',
         'attack_power': 0,
         'agility': 14,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Bloodsoul Breastplate',
         'attack_power': 0,
         'agility': 9,
         'crit_chance': 2,
         'haste': 0,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False},
        {'name': 'Cadaverlink Vest',
         'attack_power': 0,
         'agility': 29,
         'crit_chance': 0,
         'haste': 2,
         'hit': 0,
         't1': False,
         'ZG_set': False,
         'RAQ_set': False,
         't2': False,
         'TAQ_set': False,
         'r10_set': False,
         'r13_set': False,
         't3': False}
    ],
    'hand': [
        # to do
    ],
    'wrist': [
        # to do
    ],
    'waist': [
        # to do
    ],
    'legs': [
        # to do
    ],
    'feet': [
        # to do
    ],
    'finger': [
        # to do
    ],
    'trinket': [
        # to do
    ],
    'melee': [
        {'name': 'Fang of the Faceless', 'AP': 28, 'crit_chance': 1, '2h': False},
        {'name': 'Zin\'Rokh, Destroyer of Worlds', 'AP': 72, '2H': True}
    ],
    'ranged': [
        # to do
    ],
    'ammo': [
        # to do
    ]
}
